# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: fa304c1ce7b29946397a1480f728d1127e755d36f49df42bb0074b1594a2ceb34070917be8bbac9d058299afcd68b5fe518e293fe3198f792e872bd4b494e96a

test:
  secret_key_base: 05aaf91520b3826f7698353cc3e031d2c8d9e0be50c47e42ef7840547a8e349dbee2352d065283bc7da9a92b3a560e084d08fa6f7b32fd2fe060bfaf625d4b94

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
